sudo: false
language: python
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    - gcc-4.9
    - libdb++-dev
    - libdb-dev
    - libdb-java
    - libdb-java-dev
    - php5-cli
    - php5-dev
    - python-dev
    - python-pip
    - ruby-dev

cache:
  directories:
  - $HOME/.gradle
  - js/node_modules

env:
  global:
    - CXX=g++-4.9
    - GCC_COMPILER=yes
    - MCPP_HOME=${TRAVIS_BUILD_DIR}/mcpp
    - OPTIMIZE=yes
    - LMDB_REVISION=0.9.16
    - LMDB_HOME=${TRAVIS_BUILD_DIR}/lmdb-LMDB_${LMDB_REVISION}/libraries/liblmdb

python:
- "2.7"

before_install:
- git clone https://github.com/zeroc-ice/mcpp.git mcpp
- wget https://github.com/LMDB/lmdb/archive/LMDB_${LMDB_REVISION}.tar.gz
- tar xvf LMDB_${LMDB_REVISION}.tar.gz

install:
- make -C ${MCPP_HOME} -j3
- make -C ${LMDB_HOME} -j3
- pip install passlib
- make -j3

script:
- python allTests.py --debug --env --protocol=ssl

notifications:
  email: travis-ci@zeroc.com
  slack:
    secure: TywLzzH1Hx3Pb5I4s4wxbEZ9nOAPkamZDqHBOkpLSNSRa2iSk6n5GcQi5bnw0Ct59oTEytO/8fNP6mYwf5G2rrXGWpcdgSdyLMcUk6ASeO7ANv7xLKhVWbbOoVuZxFJvIG5mTYpCa3R58EtchQErzdyf3rRMN3rq/ZBmocFMcRY=
